# Generated by Django 3.1.2 on 2020-10-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20201016_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Non-Regular', 'Non-Regular')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='seva_area',
            field=models.CharField(blank=True, choices=[('Near_Home', 'Near_Home'), ('Near_Campus', 'Near_Campus')], default='', max_length=20, null=True),
        ),
    ]
